;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-dwim
        electric-newline-and-maybe-indent
        ergoemacs-copy-line-or-region
        ergoemacs-cut-line-or-region
        ergoemacs-paste
        forward-sexp
        indent-for-tab-command
        indent-rigidly
        mark-sexp
        markdown-outdent-or-delete
        nxml-electric-slash
        nxml-finish-element
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ignore
        magit-status
        org-time-stamp
        ))
